/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.manhinhchinh;

import dao.KhachHang_DAO;
import dao.NhanVien_DAO;
import dao.QuanLy_DAO;
import dao.TaiKhoan_DAO;
import java.awt.Color;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import modal.KhachHang;
import modal.NhanVien;
import modal.QuanLy;
import modal.TaiKhoan;

/**
 *
 * @author ADMIN
 */
public class ThongTinTaiKhoan extends JDialog {

    /**
     * Creates new form ThongTinTaiKhoan
     */
    private TaiKhoan taikhoan;
    private boolean capNhat = false;
    
    public ThongTinTaiKhoan(TaiKhoan taikhoan) throws SQLException {
        initComponents();
        this.taikhoan = taikhoan;
        panelDoiMatKhau.setVisible(false);
        buttonBack.setVisible(false);
        layThongTin();
    }
    
    private void layThongTinNguoiDung() throws SQLException{
        if(taikhoan.getVaiTro().equals("NhanVien")){
            NhanVien_DAO nhanVien_dao = new NhanVien_DAO();
            NhanVien nv = nhanVien_dao.layThongTinNhanVien(taikhoan.getTenNguoiDung());
        }
    }
    
    private void layThongTin() throws SQLException{
        labelTenTaiKhoan.setText(taikhoan.getTenNguoiDung());
        
        Date ngayThamGia = taikhoan.getNgayTao();
        dateChooserNgayThamGia.setDate(ngayThamGia);
            
        if(taikhoan.getVaiTro().equals("NhanVien")){
            textVaiTro.setText("Nhân viên");
            NhanVien_DAO nv_dao = new NhanVien_DAO();
            NhanVien nv = nv_dao.layThongTinNhanVien(taikhoan.getTenNguoiDung());
            textHo.setText(nv.getHo());
            textTen.setText(nv.getTen());
            textSoDienThoai.setText(nv.getSoDienThoai());
            textDiaChi.setText(nv.getDiaChi());
            Date ngaySinh = nv.getNgaySinh();
                dateChooserNgaySinh.setDate(ngaySinh);
            if(nv.getGioiTinh().equals("Nam")){
                radioNam.setSelected(true);
            }else {
                radioNu.setSelected(true);
            }
        }else{
            textVaiTro.setText("Quản lý");
            QuanLy_DAO ql_dao = new QuanLy_DAO();
            QuanLy ql = ql_dao.layThongTinQuanLy(taikhoan.getTenNguoiDung());
            textHo.setText(ql.getHo());
            textTen.setText(ql.getTen());
            textSoDienThoai.setText(ql.getSoDienThoai());
            textDiaChi.setText(ql.getDiaChi());
            textEmail.setText(ql.getEmail());
            Date ngaySinh = ql.getNgaySinh();
                dateChooserNgaySinh.setDate(ngaySinh);
            if(ql.getGioiTinh().equals("Nam")){
                radioNam.setSelected(true);
            }else {
                radioNu.setSelected(true);
            }
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupButtonGioiTinh = new javax.swing.ButtonGroup();
        panelNorth = new javax.swing.JPanel();
        labelTenTaiKhoan = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        panelThongTin = new javax.swing.JPanel();
        labelHo = new javax.swing.JLabel();
        labelTen = new javax.swing.JLabel();
        labelNgaySinh = new javax.swing.JLabel();
        labelNgayThamGia = new javax.swing.JLabel();
        labelSoDienThoai = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        labelDiaChi = new javax.swing.JLabel();
        labelVaiTro = new javax.swing.JLabel();
        textHo = new javax.swing.JTextField();
        textTen = new javax.swing.JTextField();
        textSoDienThoai = new javax.swing.JTextField();
        textEmail = new javax.swing.JTextField();
        textDiaChi = new javax.swing.JTextField();
        textVaiTro = new javax.swing.JTextField();
        dateChooserNgaySinh = new com.toedter.calendar.JDateChooser();
        dateChooserNgayThamGia = new com.toedter.calendar.JDateChooser();
        labelGioiTinh = new javax.swing.JLabel();
        radioNam = new javax.swing.JRadioButton();
        radioNu = new javax.swing.JRadioButton();
        panelDoiMatKhau = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnXacNhan = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        passCu = new javax.swing.JPasswordField();
        passMoi = new javax.swing.JPasswordField();
        passXacNhan = new javax.swing.JPasswordField();
        panelHoTro = new javax.swing.JPanel();
        btnCapNhatThongTin = new javax.swing.JButton();
        btnDoiMatKhau = new javax.swing.JButton();
        buttonBack = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        panelNorth.setBackground(new java.awt.Color(255, 255, 255));
        panelNorth.setPreferredSize(new java.awt.Dimension(600, 100));

        labelTenTaiKhoan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelTenTaiKhoan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTenTaiKhoan.setText("Tên tài khoản");
        labelTenTaiKhoan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/NhanVien.png"))); // NOI18N

        javax.swing.GroupLayout panelNorthLayout = new javax.swing.GroupLayout(panelNorth);
        panelNorth.setLayout(panelNorthLayout);
        panelNorthLayout.setHorizontalGroup(
            panelNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 791, Short.MAX_VALUE)
            .addGroup(panelNorthLayout.createSequentialGroup()
                .addGap(333, 333, 333)
                .addComponent(labelTenTaiKhoan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNorthLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(364, 364, 364))
        );
        panelNorthLayout.setVerticalGroup(
            panelNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNorthLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTenTaiKhoan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(panelNorth, java.awt.BorderLayout.PAGE_START);

        panelThongTin.setBackground(new java.awt.Color(255, 255, 255));
        panelThongTin.setPreferredSize(new java.awt.Dimension(800, 370));

        labelHo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelHo.setText("Họ: ");

        labelTen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelTen.setText("Tên: ");

        labelNgaySinh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelNgaySinh.setText("Ngày Sinh:");

        labelNgayThamGia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelNgayThamGia.setText("Ngày tham gia:");

        labelSoDienThoai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelSoDienThoai.setText("Số điện thoại:");

        labelEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelEmail.setText("Email:");

        labelDiaChi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelDiaChi.setText("Địa chỉ:");

        labelVaiTro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelVaiTro.setText("Vai trò:");

        textHo.setEditable(false);
        textHo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textHo.setEnabled(false);

        textTen.setEditable(false);
        textTen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textTen.setEnabled(false);

        textSoDienThoai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textSoDienThoai.setEnabled(false);

        textEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textEmail.setEnabled(false);

        textDiaChi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textDiaChi.setEnabled(false);

        textVaiTro.setEditable(false);
        textVaiTro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textVaiTro.setEnabled(false);

        dateChooserNgaySinh.setBackground(new java.awt.Color(255, 255, 255));
        dateChooserNgaySinh.setEnabled(false);

        dateChooserNgayThamGia.setBackground(new java.awt.Color(255, 255, 255));
        dateChooserNgayThamGia.setEnabled(false);

        labelGioiTinh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelGioiTinh.setText("Giới tính:");

        groupButtonGioiTinh.add(radioNam);
        radioNam.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        radioNam.setSelected(true);
        radioNam.setText("Nam");
        radioNam.setEnabled(false);

        groupButtonGioiTinh.add(radioNu);
        radioNu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        radioNu.setText("Nữ");
        radioNu.setEnabled(false);

        panelDoiMatKhau.setBackground(new java.awt.Color(255, 255, 255));
        panelDoiMatKhau.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Đổi mật khẩu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 15), new java.awt.Color(0, 204, 0))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Nhập mật khẩu hiện tại:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Nhập mật khẩu mới:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Xác nhận lại mật khẩu:");

        btnXacNhan.setText("Xác nhận");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDoiMatKhauLayout = new javax.swing.GroupLayout(panelDoiMatKhau);
        panelDoiMatKhau.setLayout(panelDoiMatKhauLayout);
        panelDoiMatKhauLayout.setHorizontalGroup(
            panelDoiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDoiMatKhauLayout.createSequentialGroup()
                .addGroup(panelDoiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDoiMatKhauLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelDoiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(panelDoiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDoiMatKhauLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelDoiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(passMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passCu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDoiMatKhauLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(passXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelDoiMatKhauLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(btnHuy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnXacNhan)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDoiMatKhauLayout.setVerticalGroup(
            panelDoiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDoiMatKhauLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDoiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(passCu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDoiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(passMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDoiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(passXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDoiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXacNhan)
                    .addComponent(btnHuy))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        panelHoTro.setBackground(new java.awt.Color(255, 255, 255));
        panelHoTro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hỗ trợ?", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 15), new java.awt.Color(0, 51, 204))); // NOI18N
        panelHoTro.setPreferredSize(new java.awt.Dimension(800, 270));

        btnCapNhatThongTin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCapNhatThongTin.setForeground(new java.awt.Color(0, 0, 255));
        btnCapNhatThongTin.setText("Cập nhật");
        btnCapNhatThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatThongTinActionPerformed(evt);
            }
        });

        btnDoiMatKhau.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDoiMatKhau.setForeground(new java.awt.Color(0, 204, 0));
        btnDoiMatKhau.setText("Đổi mật khẩu");
        btnDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiMatKhauActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelHoTroLayout = new javax.swing.GroupLayout(panelHoTro);
        panelHoTro.setLayout(panelHoTroLayout);
        panelHoTroLayout.setHorizontalGroup(
            panelHoTroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHoTroLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btnCapNhatThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnDoiMatKhau)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        panelHoTroLayout.setVerticalGroup(
            panelHoTroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHoTroLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelHoTroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCapNhatThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDoiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        buttonBack.setBackground(new java.awt.Color(242, 242, 242));
        buttonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/back.jpg"))); // NOI18N
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelThongTinLayout = new javax.swing.GroupLayout(panelThongTin);
        panelThongTin.setLayout(panelThongTinLayout);
        panelThongTinLayout.setHorizontalGroup(
            panelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelThongTinLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelThongTinLayout.createSequentialGroup()
                        .addGroup(panelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(labelEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(labelSoDienThoai, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(labelNgayThamGia, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(labelNgaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelTen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelHo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(panelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(textSoDienThoai, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textTen, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textHo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateChooserNgaySinh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dateChooserNgayThamGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textDiaChi, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelThongTinLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(panelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelVaiTro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textVaiTro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelThongTinLayout.createSequentialGroup()
                                        .addComponent(radioNam)
                                        .addGap(18, 18, 18)
                                        .addComponent(radioNu)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelThongTinLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addComponent(panelDoiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))))
                    .addGroup(panelThongTinLayout.createSequentialGroup()
                        .addComponent(panelHoTro, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonBack)
                        .addContainerGap())))
            .addComponent(jSeparator2)
        );
        panelThongTinLayout.setVerticalGroup(
            panelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelThongTinLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelThongTinLayout.createSequentialGroup()
                        .addGroup(panelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelHo)
                            .addComponent(textHo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTen)
                            .addComponent(textTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateChooserNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNgaySinh, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(19, 19, 19)
                        .addGroup(panelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelNgayThamGia)
                            .addComponent(dateChooserNgayThamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelSoDienThoai)
                            .addComponent(textSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelEmail)
                            .addComponent(textEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDiaChi)
                            .addComponent(textDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelThongTinLayout.createSequentialGroup()
                        .addGroup(panelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textVaiTro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelVaiTro))
                        .addGap(18, 18, 18)
                        .addGroup(panelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelGioiTinh)
                            .addComponent(radioNam)
                            .addComponent(radioNu))
                        .addGap(34, 34, 34)
                        .addComponent(panelDoiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(panelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelHoTro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelThongTinLayout.createSequentialGroup()
                        .addComponent(buttonBack)
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );

        getContentPane().add(panelThongTin, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean kiemTraDuLieu() {
        Date ngaySinh = dateChooserNgaySinh.getDate();
        String sdt = textSoDienThoai.getText();
        String diaChi = textDiaChi.getText();
        String email = textEmail.getText();

        // Kiểm tra ngày sinh
        if (ngaySinh == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn Ngày sinh", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return false;
        }

        Calendar calendar = Calendar.getInstance();
        calendar.add(Calendar.YEAR, -18);
        Date minDate = calendar.getTime();

        if (ngaySinh.after(new Date())) {
            JOptionPane.showMessageDialog(this, "Ngày sinh không được lớn hơn ngày hiện tại", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return false;
        } else if (ngaySinh.after(minDate)) {
            JOptionPane.showMessageDialog(this, "Ngày sinh phải đủ 18 tuổi trở lên", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return false;
        }

        if (sdt.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Số điện thoại", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return false;
        } else if (!sdt.matches("^0\\d{9}$")) {
            JOptionPane.showMessageDialog(this, "Số điện thoại không hợp lệ. Vui lòng nhập số điện thoại bắt đầu bằng số 0 và có 10 chữ số", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return false;
        }

        if (diaChi.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Địa chỉ", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return false;
        }

        if (taikhoan.getVaiTro().equals("QuanLy")) {
            if (email.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập Email", "Thông báo", JOptionPane.WARNING_MESSAGE);
                return false;
            } else if (!email.matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$")) {
                JOptionPane.showMessageDialog(this, "Email không hợp lệ. Vui lòng nhập đúng định dạng email", "Thông báo", JOptionPane.WARNING_MESSAGE);
                return false;
            }
        }
        
        return true;
    }


    private void btnCapNhatThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatThongTinActionPerformed
                                                 
        if (!capNhat) {
            // Kích hoạt chế độ chỉnh sửa
            btnDoiMatKhau.setVisible(false);
            textSoDienThoai.setEnabled(true);
            textDiaChi.setEnabled(true);
            dateChooserNgaySinh.setEnabled(true);
            buttonBack.setVisible(true);

            if (taikhoan.getVaiTro().equals("QuanLy")) {
                textEmail.setEnabled(true);
            }

            JOptionPane.showMessageDialog(this, "Hãy sửa các thông tin cần sửa", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            capNhat = true;
        } else {
            if (kiemTraDuLieu()) {
                boolean suaThanhCong = false;

                if (taikhoan.getVaiTro().equals("NhanVien")) {
                    suaThanhCong = new NhanVien_DAO().suaThongTinNhanVien2(taikhoan.getTenNguoiDung(),
                            new java.sql.Date(dateChooserNgaySinh.getDate().getTime()),textDiaChi.getText(),
                            textSoDienThoai.getText());
                } else if (taikhoan.getVaiTro().equals("QuanLy")) {
                    suaThanhCong = new QuanLy_DAO().suaThongTinQuanLy(taikhoan.getTenNguoiDung(),
                            new java.sql.Date(dateChooserNgaySinh.getDate().getTime()), textDiaChi.getText(),
                            textEmail.getText(),textSoDienThoai.getText());
                }

                if (suaThanhCong) {
                    JOptionPane.showMessageDialog(this, "Cập nhật thông tin thành công", "Thành công", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Lỗi khi thực hiện", "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
                
            // Tắt chế độ chỉnh sửa
            back();
            }
        }
    }//GEN-LAST:event_btnCapNhatThongTinActionPerformed

    private void btnDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiMatKhauActionPerformed
        panelDoiMatKhau.setVisible(true);
        panelHoTro.setVisible(false);
    }//GEN-LAST:event_btnDoiMatKhauActionPerformed

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        String pCu = new String(passCu.getPassword());
        String pMoi = new String(passMoi.getPassword());
        String pXacNhan = new String(passXacNhan.getPassword());

        if (pCu.isEmpty() || pMoi.isEmpty() || pXacNhan.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (pMoi.length() < 6) {
            JOptionPane.showMessageDialog(this, "Mật khẩu mới phải có ít nhất 6 ký tự!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (!pMoi.equals(pXacNhan)) {
            JOptionPane.showMessageDialog(this, "Mật khẩu mới và xác nhận mật khẩu không khớp!", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (!pCu.equals(taikhoan.getMatKhau())) {
            JOptionPane.showMessageDialog(this, "Mật khẩu cũ không đúng!", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return;
        }

        TaiKhoan_DAO taiKhoan_DAO = new TaiKhoan_DAO();
        try {
            taiKhoan_DAO.capNhatMatKhau(taikhoan.getTenNguoiDung(), pMoi);
            JOptionPane.showMessageDialog(this, "Cập nhật mật khẩu thành công!", "Thành công", JOptionPane.INFORMATION_MESSAGE);
            huy();
        } catch (Exception ex) {
            Logger.getLogger(ThongTinTaiKhoan.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Cập nhật mật khẩu thất bại. Vui lòng thử lại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        huy();
    }//GEN-LAST:event_btnHuyActionPerformed

    private void huy(){
        panelDoiMatKhau.setVisible(false);
        panelHoTro.setVisible(true);
        passCu.setText("");
        passMoi.setText("");
        passXacNhan.setText("");
    }
    
    private void back(){
        btnDoiMatKhau.setVisible(true);
        textSoDienThoai.setEnabled(false);
        textDiaChi.setEnabled(false);
        dateChooserNgaySinh.setEnabled(false);
        buttonBack.setVisible(false);
        textEmail.setEnabled(false);
        capNhat = false;
    }
    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        back();
    }//GEN-LAST:event_buttonBackActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ThongTinTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ThongTinTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ThongTinTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ThongTinTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ThongTinTaiKhoan().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhatThongTin;
    private javax.swing.JButton btnDoiMatKhau;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JButton buttonBack;
    private com.toedter.calendar.JDateChooser dateChooserNgaySinh;
    private com.toedter.calendar.JDateChooser dateChooserNgayThamGia;
    private javax.swing.ButtonGroup groupButtonGioiTinh;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelDiaChi;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelGioiTinh;
    private javax.swing.JLabel labelHo;
    private javax.swing.JLabel labelNgaySinh;
    private javax.swing.JLabel labelNgayThamGia;
    private javax.swing.JLabel labelSoDienThoai;
    private javax.swing.JLabel labelTen;
    private javax.swing.JLabel labelTenTaiKhoan;
    private javax.swing.JLabel labelVaiTro;
    private javax.swing.JPanel panelDoiMatKhau;
    private javax.swing.JPanel panelHoTro;
    private javax.swing.JPanel panelNorth;
    private javax.swing.JPanel panelThongTin;
    private javax.swing.JPasswordField passCu;
    private javax.swing.JPasswordField passMoi;
    private javax.swing.JPasswordField passXacNhan;
    private javax.swing.JRadioButton radioNam;
    private javax.swing.JRadioButton radioNu;
    private javax.swing.JTextField textDiaChi;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textHo;
    private javax.swing.JTextField textSoDienThoai;
    private javax.swing.JTextField textTen;
    private javax.swing.JTextField textVaiTro;
    // End of variables declaration//GEN-END:variables
}
