/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.quanlydatban;

import dao.BanAn_DAO;
import java.util.List;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author ACER
 */
public class BanDuocGopDialog extends javax.swing.JDialog {

    /**
     * Creates new form BanDuocGopDialog
     */
    public BanDuocGopDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponentss();
        hienThiDanhSachBanDuocGop();
    }
private JTextArea textArea;
    private JButton btnClose;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initComponentss() {
        
        // Tạo các thành phần giao diện
        textArea = new JTextArea(20, 40);
        textArea.setEditable(false);
        JScrollPane scrollPane = new JScrollPane(textArea);
      btnClose = new JButton("Đóng");
        btnClose.addActionListener(e -> dispose());

        // Tạo panel cho nút Đóng
        JPanel panel = new JPanel();
        panel.setLayout(new BoxLayout(panel, BoxLayout.X_AXIS));

        // Thêm không gian trống bên trái và bên phải nút Đóng để căn giữa
        panel.add(Box.createHorizontalGlue());  // Không gian trống bên trái
        panel.add(btnClose);
        panel.add(Box.createHorizontalGlue());  // Không gian trống bên phải

        // Cấu hình layout chính của JDialog
        setLayout(new BoxLayout(getContentPane(), BoxLayout.Y_AXIS));
        add(scrollPane);
        add(panel);  // Thêm panel có nút Đóng vào



        setTitle("Danh sách các bàn đã được gộp");
        setSize(500, 400);
       setLocationRelativeTo(null); 
    }
    
    private void hienThiDanhSachBanDuocGop() {
        // Sử dụng DAO để lấy danh sách bàn gộp
        BanAn_DAO banDAO = new BanAn_DAO();
        List<String> danhSachBanDuocGop = banDAO.getDanhSachBanDuocGop();

        // Hiển thị danh sách các bàn gộp trong TextArea
        if (danhSachBanDuocGop.isEmpty()) {
            textArea.setText("Hiện tại không có bàn nào được gộp.");
        } else {
            StringBuilder sb = new StringBuilder();
            for (String banGop : danhSachBanDuocGop) {
                sb.append(banGop).append("\n");
            }
            textArea.setText(sb.toString());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BanDuocGopDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BanDuocGopDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BanDuocGopDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BanDuocGopDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BanDuocGopDialog dialog = new BanDuocGopDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
