// Nguyen Duc Hau 13/10/2024

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.quanlyhoadon;

import dao.HoaDon_DAO;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.geom.RoundRectangle2D;
import modal.HoaDon;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
/**
 *
 * @author ADMIN
 */
public class ManHinhThanhToanHoaDon extends javax.swing.JPanel {
    
    
    /**
     * Creates new form ManHinhThanhToanHoaDon
     */
    public ManHinhThanhToanHoaDon() {
        initComponents();
       docDuLieuDSHoaDon();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBoxTrangThaiHoaDon = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldMaBan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldSoDienThoai = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButtonreSet = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelSLChuaThanhToan = new javax.swing.JLabel();
        jLabelSLDangXuLy = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Trạng thái:");

        jComboBoxTrangThaiHoaDon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jComboBoxTrangThaiHoaDon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chưa thanh toán", "Đang xử lý" }));
        jComboBoxTrangThaiHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTrangThaiHoaDonActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(204, 255, 255));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(0, 4, 5, 5));
        jScrollPane1.setViewportView(jPanel2);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 102, 102));
        jPanel4.setPreferredSize(new java.awt.Dimension(88, 58));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(255, 204, 51));
        jPanel5.setPreferredSize(new java.awt.Dimension(88, 58));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 127, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Đang xử lý");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Chưa thanh toán");

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Mã bàn:");

        jTextFieldMaBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMaBanActionPerformed(evt);
            }
        });
        jTextFieldMaBan.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTextFieldMaBanPropertyChange(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Số điện thoại:");

        jTextFieldSoDienThoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSoDienThoaiActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search (1) (1).png"))); // NOI18N
        jButton1.setText("Tìm kiếm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldMaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldMaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(65, 65, 65)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(447, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jButtonreSet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/refesh.png"))); // NOI18N
        jButtonreSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonreSetActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Số lượng hóa đơn chưa thanh toán:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Số lượng hóa đơn đang xử lý:");

        jLabelSLChuaThanhToan.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSLChuaThanhToan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelSLChuaThanhToan.setForeground(new java.awt.Color(255, 51, 51));
        jLabelSLChuaThanhToan.setText("jLabel8");

        jLabelSLDangXuLy.setBackground(new java.awt.Color(255, 51, 51));
        jLabelSLDangXuLy.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelSLDangXuLy.setForeground(new java.awt.Color(255, 51, 51));
        jLabelSLDangXuLy.setText("jLabel8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelSLChuaThanhToan)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelSLDangXuLy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxTrangThaiHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonreSet)
                        .addGap(69, 69, 69))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonreSet, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxTrangThaiHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel7)
                        .addComponent(jLabelSLChuaThanhToan)
                        .addComponent(jLabelSLDangXuLy)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
 

    private void jComboBoxTrangThaiHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTrangThaiHoaDonActionPerformed
        // TODO add your handling code here:
        locHoaDonTheoTrangThai();
    }//GEN-LAST:event_jComboBoxTrangThaiHoaDonActionPerformed

    private void jTextFieldSoDienThoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSoDienThoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSoDienThoaiActionPerformed

    private void jButtonreSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonreSetActionPerformed
        // TODO add your handling code here:
        resetDanhSachHoaDon();
    }//GEN-LAST:event_jButtonreSetActionPerformed

    private void jTextFieldMaBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMaBanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMaBanActionPerformed

    private void jTextFieldMaBanPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTextFieldMaBanPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMaBanPropertyChange

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        timKiemTheoMaBanHoacSoDienThoai();
        jTextFieldMaBan.setText("");
        jTextFieldSoDienThoai.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonreSet;
    private javax.swing.JComboBox<String> jComboBoxTrangThaiHoaDon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelSLChuaThanhToan;
    private javax.swing.JLabel jLabelSLDangXuLy;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldMaBan;
    private javax.swing.JTextField jTextFieldSoDienThoai;
    // End of variables declaration//GEN-END:variables
    public JButton buttonThanhToan;
public void docDuLieuDSHoaDon() {
    // Lấy danh sách hóa đơn từ cơ sở dữ liệu
    HoaDon_DAO hoaDonDao = new HoaDon_DAO();
    List<HoaDon> dsHoaDon = hoaDonDao.getAllHoaDonThongTin();
    
     // Khởi tạo biến đếm
    int countChuaThanhToan = 0;
    int countDangXuLy = 0;

    
    for (HoaDon hoaDon : dsHoaDon) {
        
         if ("Chưa thanh toán".equals(hoaDon.getTrangThaiThanhToan())) {
            countChuaThanhToan++;
        } else if ("Đang xử lý".equals(hoaDon.getTrangThaiThanhToan())) {
            countDangXuLy++;
        }
        // Tạo panel mới cho mỗi hóa đơn
        JPanel newPanel = new JPanel();
        newPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        newPanel.setPreferredSize(new java.awt.Dimension(200, 200));
        newPanel.setLayout(new BorderLayout()); // Sử dụng BorderLayout

        // Panel trạng thái
        JPanel panelTrangThai = new JPanel();
        // Thiết lập màu sắc cho panel trạng thái dựa vào trạng thái thanh toán
        switch (hoaDon.getTrangThaiThanhToan()) {
            case "Đã thanh toán":
                panelTrangThai.setBackground(new java.awt.Color(51, 204, 51)); // Màu xanh
                break;
            case "Chưa thanh toán":
                panelTrangThai.setBackground(new java.awt.Color(255, 102, 102)); // Màu đỏ
                break;
            case "Đang xử lý":
                panelTrangThai.setBackground(new java.awt.Color(255, 204, 51)); // Màu vàng
                break;
            default:
                panelTrangThai.setBackground(new java.awt.Color(240, 240, 240)); // Màu xám mặc định
                break;
        }
        panelTrangThai.setPreferredSize(new java.awt.Dimension(32, 30)); // Kích thước panel trạng thái

        // Icon button
        JButton iconButton = new JButton();
        iconButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon_hoadon_new (1).png"))); // NOI18N
        iconButton.setPreferredSize(new java.awt.Dimension(140, 120)); // Kích thước icon lớn hơn
//        iconButton.setHorizontalAlignment(SwingConstants.CENTER); // Căn giữa icon
        iconButton.setBackground(Color.white);

        // Tạo JPanel cho thông tin
        JPanel infoPanel = new JPanel();
        infoPanel.setLayout(new BoxLayout(infoPanel, BoxLayout.X_AXIS)); // Sắp xếp theo chiều ngang

        // TextField cho Mã bàn và Số điện thoại
        JLabel maBanField = new JLabel();
        maBanField.setFont(new java.awt.Font("Segoe UI", 0, 14));
        maBanField.setText("Mã bàn: " + hoaDon.getBanAn().getMaBan());  // Lấy mã bàn từ hóa đơn

        JLabel soDienThoaiField = new JLabel();
        soDienThoaiField.setFont(new java.awt.Font("Segoe UI", 0, 14));
        soDienThoaiField.setText("SĐT: " + hoaDon.getKhachHang().getSoDienThoai());  // Lấy số điện thoại từ khách hàng
           infoPanel.add(Box.createHorizontalStrut(20)); // Khoảng cách giữa Mã bàn và SĐT
        infoPanel.add(maBanField);
        infoPanel.add(Box.createHorizontalStrut(10)); // Khoảng cách giữa Mã bàn và SĐT
        infoPanel.add(soDienThoaiField);

        // Tạo JPanel cho hàng đầu (bao gồm panel trạng thái và thông tin)
        JPanel headerPanel = new JPanel();
        headerPanel.setLayout(new BorderLayout()); // Sử dụng BorderLayout cho headerPanel

        // Thêm panel trạng thái vào headerPanel
        headerPanel.add(panelTrangThai, BorderLayout.WEST); // Panel trạng thái ở bên trái
        headerPanel.add(infoPanel, BorderLayout.CENTER); // Thông tin ở giữa

        // Tạo JPanel cho các button
        JPanel buttonPanel = new JPanel();
        buttonPanel.setLayout(new FlowLayout()); // Sử dụng FlowLayout
        buttonThanhToan = new JButton("Thanh toán");
        

        buttonThanhToan.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
        // Xử lý sự kiện khi nhấn nút  
            FrameThanhToan frame = new FrameThanhToan(hoaDon);
            frame.setVisible(true);
    }
});


        buttonThanhToan.setFont(new java.awt.Font("Segoe UI", 0, 14));
        buttonThanhToan.setPreferredSize(new java.awt.Dimension(120, 40)); // Kích thước button thanh toán
        JButton buttonXemHoaDon = new JButton("Xem hóa đơn");
   
        buttonXemHoaDon.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
        // Xử lý sự kiện khi nhấn nút  
            FrameXemHoaDon frame = new FrameXemHoaDon(hoaDon);
            frame.setVisible(true);
    }
});
        buttonXemHoaDon.setFont(new java.awt.Font("Segoe UI", 0, 14));
        buttonXemHoaDon.setPreferredSize(new java.awt.Dimension(120, 40)); // Kích thước button xem hóa đơn

        buttonPanel.add(buttonThanhToan);
        buttonPanel.add(buttonXemHoaDon);

        // Thêm các thành phần vào newPanel
        newPanel.add(headerPanel, BorderLayout.NORTH); // Thêm headerPanel ở trên cùng
        newPanel.add(iconButton, BorderLayout.CENTER); // Icon ở giữa
        newPanel.add(buttonPanel, BorderLayout.SOUTH); // Các button ở dưới cùng

        // Thêm panel mới vào jPanel2
        jPanel2.add(newPanel);
        
        
    }
    
    // Cập nhật lại jPanel2 để hiển thị tất cả các panel mới
    jPanel2.revalidate();
    jPanel2.repaint();
    
    jLabelSLChuaThanhToan.setText(String.valueOf(countChuaThanhToan));
    jLabelSLDangXuLy.setText(String.valueOf(countDangXuLy));
}
// hàm lọc theo combobox
private void locHoaDonTheoTrangThai() {
    // Lấy trạng thái được chọn trong ComboBox
    String trangThaiChon = jComboBoxTrangThaiHoaDon.getSelectedItem().toString();

    // Xóa tất cả các panel hiện tại khỏi jPanel2
    jPanel2.removeAll();
// Lấy danh sách hóa đơn từ cơ sở dữ liệu
    HoaDon_DAO hoaDonDao = new HoaDon_DAO();
    List<HoaDon> dsHoaDon = hoaDonDao.getAllHoaDonThongTin();
    // Lặp qua danh sách hóa đơn và lọc theo trạng thái thanh toán
    for (HoaDon hoaDon : dsHoaDon) {
        String trangThaiThanhToan = hoaDon.getTrangThaiThanhToan();

        // Kiểm tra xem trạng thái thanh toán của hóa đơn có khớp với trạng thái đã chọn không
        if (trangThaiThanhToan.equals(trangThaiChon)) {
            // Tạo panel mới cho mỗi hóa đơn khớp với trạng thái
            JPanel newPanel = new JPanel();
            newPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
            newPanel.setPreferredSize(new java.awt.Dimension(200, 200));
            newPanel.setLayout(new BorderLayout());

            // Panel trạng thái
            JPanel panelTrangThai = new JPanel();
            switch (hoaDon.getTrangThaiThanhToan()) {
                case "Đã thanh toán":
                    panelTrangThai.setBackground(new java.awt.Color(51, 204, 51)); // Màu xanh
                    break;
                case "Chưa thanh toán":
                    panelTrangThai.setBackground(new java.awt.Color(255, 102, 102)); // Màu đỏ
                    break;
                case "Đang xử lý":
                    panelTrangThai.setBackground(new java.awt.Color(255, 204, 51)); // Màu vàng
                    break;
                default:
                    panelTrangThai.setBackground(new java.awt.Color(240, 240, 240)); // Màu xám mặc định
                    break;
            }
            panelTrangThai.setPreferredSize(new java.awt.Dimension(32, 30)); // Kích thước panel trạng thái

            // Icon button
            JButton iconButton = new JButton();
            iconButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon_hoadon_new (1).png"))); // Icon cho hóa đơn
            iconButton.setPreferredSize(new java.awt.Dimension(140, 120));
            iconButton.setBackground(Color.white);

            // Tạo JPanel cho thông tin
            JPanel infoPanel = new JPanel();
            infoPanel.setLayout(new BoxLayout(infoPanel, BoxLayout.X_AXIS));
            JLabel maBanField = new JLabel();
            maBanField.setFont(new java.awt.Font("Segoe UI", 0, 14));
            maBanField.setText("Mã bàn: " + hoaDon.getBanAn().getMaBan());

            JLabel soDienThoaiField = new JLabel();
            soDienThoaiField.setFont(new java.awt.Font("Segoe UI", 0, 14));
            soDienThoaiField.setText("SĐT: " + hoaDon.getKhachHang().getSoDienThoai());

            infoPanel.add(Box.createHorizontalStrut(20)); // Khoảng cách
            infoPanel.add(maBanField);
            infoPanel.add(Box.createHorizontalStrut(10)); // Khoảng cách
            infoPanel.add(soDienThoaiField);

            // Tạo JPanel cho hàng đầu
            JPanel headerPanel = new JPanel();
            headerPanel.setLayout(new BorderLayout());
            headerPanel.add(panelTrangThai, BorderLayout.WEST);
            headerPanel.add(infoPanel, BorderLayout.CENTER);

            // Tạo JPanel cho các button
            JPanel buttonPanel = new JPanel();
            buttonPanel.setLayout(new FlowLayout());

            // Nút Thanh Toán
            JButton buttonThanhToan = new JButton("Thanh toán");
            buttonThanhToan.setFont(new java.awt.Font("Segoe UI", 0, 14));
            buttonThanhToan.setPreferredSize(new java.awt.Dimension(120, 40));
            buttonThanhToan.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    // Mở Frame thanh toán với hóa đơn hiện tại
                    FrameThanhToan frame = new FrameThanhToan(hoaDon);
                    frame.setVisible(true);
                }
            });

            // Nút Xem Hóa Đơn
            JButton buttonXemHoaDon = new JButton("Xem hóa đơn");
            buttonXemHoaDon.setFont(new java.awt.Font("Segoe UI", 0, 14));
            buttonXemHoaDon.setPreferredSize(new java.awt.Dimension(120, 40));
 buttonXemHoaDon.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
        // Xử lý sự kiện khi nhấn nút  
            FrameXemHoaDon frame = new FrameXemHoaDon(hoaDon);
            frame.setVisible(true);
    }
});

            buttonPanel.add(buttonThanhToan);
            buttonPanel.add(buttonXemHoaDon);

            // Thêm các thành phần vào newPanel
            newPanel.add(headerPanel, BorderLayout.NORTH);
            newPanel.add(iconButton, BorderLayout.CENTER);
            newPanel.add(buttonPanel, BorderLayout.SOUTH);

            // Thêm panel mới vào jPanel2
            jPanel2.add(newPanel);
        }
    }

    // Cập nhật lại jPanel2 để hiển thị tất cả các panel khớp với trạng thái
    jPanel2.revalidate();
    jPanel2.repaint();
}


// hàm reset
private void resetDanhSachHoaDon() {
    // Xóa tất cả các panel hiện tại khỏi jPanel2
    jPanel2.removeAll();
  docDuLieuDSHoaDon();
}

// hàm tìm
 private void timKiemTheoMaBanHoacSoDienThoai() {
    // Lấy nội dung người dùng đã nhập vào JTextField
    String maBanTuKhoa = jTextFieldMaBan.getText().trim().toLowerCase();
    String soDienThoaiTuKhoa = jTextFieldSoDienThoai.getText().trim().toLowerCase();
    if (maBanTuKhoa.isEmpty() && soDienThoaiTuKhoa.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập mã bàn hoặc số điện thoại để tìm kiếm!", "Thông báo", JOptionPane.WARNING_MESSAGE);
        return;
    }

    
    // Xóa tất cả các panel hiện tại khỏi jPanel2
    jPanel2.removeAll();
    // Lấy danh sách hóa đơn từ cơ sở dữ liệu
    HoaDon_DAO hoaDonDao = new HoaDon_DAO();
    List<HoaDon> dsHoaDon = hoaDonDao.getAllHoaDonThongTin();
    // Lặp qua danh sách hóa đơn và tìm kiếm theo mã bàn và số điện thoại
    for (HoaDon hoaDon : dsHoaDon) {
        String maBan = hoaDon.getBanAn().getMaBan().toLowerCase();
        String soDienThoai = hoaDon.getKhachHang().getSoDienThoai().toLowerCase();

        // Kiểm tra xem cả hai từ khóa có khớp với mã bàn và số điện thoại hay không
        if (maBan.contains(maBanTuKhoa) && soDienThoai.contains(soDienThoaiTuKhoa)) {
            // Tạo panel mới cho mỗi hóa đơn khớp với từ khóa
            JPanel newPanel = new JPanel();
            newPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
            newPanel.setPreferredSize(new java.awt.Dimension(200, 200));
            newPanel.setLayout(new BorderLayout());

            // Panel trạng thái
            JPanel panelTrangThai = new JPanel();
            switch (hoaDon.getTrangThaiThanhToan()) {
                case "Đã thanh toán":
                    panelTrangThai.setBackground(new java.awt.Color(51, 204, 51)); // Màu xanh
                    break;
                case "Chưa thanh toán":
                    panelTrangThai.setBackground(new java.awt.Color(255, 102, 102)); // Màu đỏ
                    break;
                case "Đang xử lý":
                    panelTrangThai.setBackground(new java.awt.Color(255, 204, 51)); // Màu vàng
                    break;
                default:
                    panelTrangThai.setBackground(new java.awt.Color(240, 240, 240)); // Màu xám mặc định
                    break;
            }
            panelTrangThai.setPreferredSize(new java.awt.Dimension(32, 30)); // Kích thước panel trạng thái

            // Icon button
            JButton iconButton = new JButton();
            iconButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon_hoadon_new (1).png"))); // Icon cho hóa đơn
            iconButton.setPreferredSize(new java.awt.Dimension(140, 120));
            iconButton.setBackground(Color.white);

            // Tạo JPanel cho thông tin
            JPanel infoPanel = new JPanel();
            infoPanel.setLayout(new BoxLayout(infoPanel, BoxLayout.X_AXIS));
            JLabel maBanField = new JLabel();
            maBanField.setFont(new java.awt.Font("Segoe UI", 0, 14));
            maBanField.setText("Mã bàn: " + hoaDon.getBanAn().getMaBan());

            JLabel soDienThoaiField = new JLabel();
            soDienThoaiField.setFont(new java.awt.Font("Segoe UI", 0, 14));
            soDienThoaiField.setText("SĐT: " + hoaDon.getKhachHang().getSoDienThoai());

            infoPanel.add(Box.createHorizontalStrut(20)); // Khoảng cách
            infoPanel.add(maBanField);
            infoPanel.add(Box.createHorizontalStrut(10)); // Khoảng cách
            infoPanel.add(soDienThoaiField);

            // Tạo JPanel cho hàng đầu
            JPanel headerPanel = new JPanel();
            headerPanel.setLayout(new BorderLayout());
            headerPanel.add(panelTrangThai, BorderLayout.WEST);
            headerPanel.add(infoPanel, BorderLayout.CENTER);

            // Tạo JPanel cho các button
            JPanel buttonPanel = new JPanel();
            buttonPanel.setLayout(new FlowLayout());

            // Nút Thanh Toán
            JButton buttonThanhToan = new JButton("Thanh toán");
            buttonThanhToan.setFont(new java.awt.Font("Segoe UI", 0, 14));
            buttonThanhToan.setPreferredSize(new java.awt.Dimension(120, 40));
            buttonThanhToan.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    // Mở Frame thanh toán với hóa đơn hiện tại
                    FrameThanhToan frame = new FrameThanhToan(hoaDon);
                    frame.setVisible(true);
                }
            });

            // Nút Xem Hóa Đơn
            JButton buttonXemHoaDon = new JButton("Xem hóa đơn");
            buttonXemHoaDon.setFont(new java.awt.Font("Segoe UI", 0, 14));
            buttonXemHoaDon.setPreferredSize(new java.awt.Dimension(120, 40));
 buttonXemHoaDon.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
        // Xử lý sự kiện khi nhấn nút  
            FrameXemHoaDon frame = new FrameXemHoaDon(hoaDon);
            frame.setVisible(true);
    }
});

            buttonPanel.add(buttonThanhToan);
            buttonPanel.add(buttonXemHoaDon);

            // Thêm các thành phần vào newPanel
            newPanel.add(headerPanel, BorderLayout.NORTH);
            newPanel.add(iconButton, BorderLayout.CENTER);
            newPanel.add(buttonPanel, BorderLayout.SOUTH);

            // Thêm panel mới vào jPanel2
            jPanel2.add(newPanel);
        }
    }

    // Cập nhật lại jPanel2 để hiển thị tất cả các panel khớp với từ khóa
    jPanel2.revalidate();
    jPanel2.repaint();
}


   
}



   
